# Generated by Django 3.2.16 on 2022-10-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_song_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='name',
        ),
    ]
